[package]
name = "http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
clippy = "0.0.302"
tokio = { version = "1.37.0", features = ["full"]}
tokio-stream = "0.1.15"
url = "2.5.0"
futures = "0.3.30"
async-backtrace = "0.2.7"
bytes = "1.6.0"
strum = "0.26"
strum_macros = "0.26.2"
tokio-util = { version = "0.7.11", features = ["codec"] }
#tracing = "0.1.40"
#tracing-subscriber = "0.3.18"